package controller;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.Stage;
import lsc482.lsc482.InventoryApplication;
import model.*;

import java.io.IOException;
import java.net.URL;
import java.util.Optional;
import java.util.ResourceBundle;

import static model.Inventory.getAllParts;
import static model.Inventory.lookupPart;

/** This class creates a form for a user to add a new product to the inventory.
 *
 * @author Louie Sanchez
 *
 */
public class AddProductFormController implements Initializable {

    Stage stage;
    Parent scene;

    @FXML
    private ObservableList<Part> selectedProductAssociatedParts = FXCollections.observableArrayList();
    @FXML
    private TextField productIdTXT;
    @FXML
    private TextField productNameTXT;
    @FXML
    private TextField productInventoryTXT;
    @FXML
    private TextField productPriceTXT;
    @FXML
    private TextField productMaxTXT;
    @FXML
    private TextField productMinTXT;
    @FXML
    private TextField searchPartsTableTXT;
    @FXML
    private TableColumn<Part, Integer> partIdCOL;
    @FXML
    private TableColumn<Part, String> partNameCOL;
    @FXML
    private TableColumn<Part, Double> partCostCOL;
    @FXML
    private TableColumn<Part, Integer> partInventoryLevelCOL;
    @FXML
    private TableView<Part> associatedPartsTableView;
    @FXML
    private TableView<Part> partsTableView;
    @FXML
    private TableColumn associatedPartIdCOL;
    @FXML
    private TableColumn associatedPartNameCOL;
    @FXML
    private TableColumn associatedPartInventoryLevelCOL;
    @FXML
    private TableColumn associatedPartCostCOL;
    @FXML
    private Label errorTextSearchBar;
    @FXML
    private Label errorText;

    /** This saves a user's input of the textfields and creates a new product. After creating a new product, a user is redirected back to the main form. */
    @FXML
    void onActionSaveProduct(ActionEvent event) throws IOException {
        try {
            int autoGeneratedProductId = 1001;
            for(Product product : Inventory.getAllProducts()) {
                while(autoGeneratedProductId == product.getId()){
                    autoGeneratedProductId++;
                }
            }

            int id = autoGeneratedProductId;
            String name = productNameTXT.getText();
            int stock = Integer.parseInt(productInventoryTXT.getText());
            Double price = Double.parseDouble(productPriceTXT.getText());
            int max = Integer.parseInt(productMaxTXT.getText());
            int min = Integer.parseInt(productMinTXT.getText());

            if (max < min || stock < min || max < stock) {
                Alert alert = new Alert(Alert.AlertType.ERROR);
                alert.setTitle("Error");
                alert.setContentText("Min should be less than Max; and Inv should be between those two values.");
                alert.showAndWait();
                return;
            }

            Product newProduct = new Product(id, name, price, stock, min, max);
            for(Part part : selectedProductAssociatedParts) {
                newProduct.addAssociatedPart(part);
            }
            Inventory.addProduct(newProduct);

            stage = (Stage)((Button)event.getSource()).getScene().getWindow();
            scene = FXMLLoader.load(InventoryApplication.class.getResource("mainform-view.fxml"));
            stage.setScene(new Scene(scene));
            stage.show();
        }
        catch(NumberFormatException exception) {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Error");
            alert.setContentText("Please enter valid values into the text fields.");
            alert.showAndWait();
        }
    }

    /** This lets a user search the parts table by part ID or part name. */
    @FXML
    void onActionSearchParts(ActionEvent event) {
        try {
            errorTextSearchBar.setText("");
            String query = searchPartsTableTXT.getText();
            ObservableList<Part> parts = lookupPart(query);

            if (parts.size() == 0) {
                int idQuery = Integer.parseInt(query);
                parts = lookupPart(idQuery);
            }

            partsTableView.setItems(parts);
            searchPartsTableTXT.setText("");

            if(parts.size() == 0) {
                errorTextSearchBar.setText("Part not found.");
                partsTableView.setItems(getAllParts());
            }
        }
        catch(NumberFormatException exception) {
            errorTextSearchBar.setText("Part not found.");
            partsTableView.setItems(getAllParts());
        }
    }

    /** This adds a user selected part from the parts table to the associated list of a product. */
    @FXML
    void onActionAddAssociatedPart(ActionEvent event) {
        selectedProductAssociatedParts.add(partsTableView.getSelectionModel().getSelectedItem());
        associatedPartsTableView.setItems(selectedProductAssociatedParts);
    }

    /** This removes a user selected part from the the associated list of a product. */
    @FXML
    void onActionRemoveAssociatedPart(ActionEvent event) {
        Alert alert = new Alert(Alert.AlertType.CONFIRMATION, "This will remove the associated part. Do you want to continue?");

        Optional<ButtonType> result = alert.showAndWait();

        if(result.isPresent() && result.get() == ButtonType.OK) {
            selectedProductAssociatedParts.remove(associatedPartsTableView.getSelectionModel().getSelectedItem());
        }
    }

    /** This redirects a user back to the main form. */
    @FXML
    void onActionMainForm(ActionEvent event) throws IOException {
        Alert alert = new Alert(Alert.AlertType.CONFIRMATION, "This will clear all text fields. Do you want to continue?");

        Optional<ButtonType> result = alert.showAndWait();

        if(result.isPresent() && result.get() == ButtonType.OK) {
            stage = (Stage) ((Button) event.getSource()).getScene().getWindow();
            scene = FXMLLoader.load(InventoryApplication.class.getResource("mainform-view.fxml"));
            stage.setScene(new Scene(scene));
            stage.show();
        }
    }

    /** This initializes the parts and associated parts tables. */
    @Override
    public void initialize(URL url, ResourceBundle rb) {

        partsTableView.setItems(Inventory.getAllParts());
        partIdCOL.setCellValueFactory(new PropertyValueFactory<>("id"));
        partNameCOL.setCellValueFactory(new PropertyValueFactory<>("name"));
        partCostCOL.setCellValueFactory(new PropertyValueFactory<>("price"));
        partInventoryLevelCOL.setCellValueFactory(new PropertyValueFactory<>("stock"));

        associatedPartIdCOL.setCellValueFactory(new PropertyValueFactory<>("id"));
        associatedPartNameCOL.setCellValueFactory(new PropertyValueFactory<>("name"));
        associatedPartCostCOL.setCellValueFactory(new PropertyValueFactory<>("price"));
        associatedPartInventoryLevelCOL.setCellValueFactory(new PropertyValueFactory<>("stock"));
    }

}