package controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.stage.Stage;
import lsc482.lsc482.InventoryApplication;
import model.InHouse;
import model.Inventory;
import model.Outsourced;
import model.Part;

import java.io.IOException;
import java.util.Optional;

/** This class creates a form for a user to add a new part to the inventory.
 *
 * @author Louie Sanchez
 *
 */
public class AddPartFormController {

    Stage stage;
    Parent scene;

    @FXML
    private RadioButton inhouseRADIOBTN;
    @FXML
    private RadioButton outsourcedRADIOBRN;
    @FXML
    private ToggleGroup addPartRadioGroup;
    @FXML
    private Label partMachineIdLBL;
    @FXML
    private TextField partIdTXT;
    @FXML
    private TextField partNameTXT;
    @FXML
    private TextField partInvTXT;
    @FXML
    private TextField partCostTXT;
    @FXML
    private TextField partMaxTXT;
    @FXML
    private TextField partMinTXT;
    @FXML
    private TextField partCompanyNameTXT;
    @FXML
    private Label partCompanyNameLBL;
    @FXML
    private TextField partMachineIdTXT;
    @FXML
    private Label errorText;

    /** This makes the machine label and machine textfield visible for a user to input the information of an inhouse part. */
    @FXML
    protected void onActionInhouse() {
        partMachineIdLBL.setVisible(true);
        partMachineIdTXT.setVisible(true);
        partCompanyNameLBL.setVisible(false);
        partCompanyNameTXT.setVisible(false);
    }

    /** This makes the company label and company textfield visible for a user to input the information of an outsourced part. */
    @FXML
    protected void onActionOutsourced() {
        partMachineIdLBL.setVisible(false);
        partMachineIdTXT.setVisible(false);
        partCompanyNameLBL.setVisible(true);
        partCompanyNameTXT.setVisible(true);
    }

    /** This saves a user's input of the textfields and creates a new part. After creating a new part, a user is redirected back to the main form. */
    @FXML
    void onActionSavePart(ActionEvent event) throws IOException {
        try {
            int autoGeneratedPartId = 1;
            for(Part part : Inventory.getAllParts()) {
                while(autoGeneratedPartId == part.getId()){
                    autoGeneratedPartId++;
                }
            }

            int id = autoGeneratedPartId;
            String name = partNameTXT.getText();
            int stock = Integer.parseInt(partInvTXT.getText());
            Double price = Double.parseDouble(partCostTXT.getText());
            int max = Integer.parseInt(partMaxTXT.getText());
            int min = Integer.parseInt(partMinTXT.getText());

            if (max < min || stock < min || max < stock) {
                Alert alert = new Alert(Alert.AlertType.ERROR);
                alert.setTitle("Error");
                alert.setContentText("Min should be less than Max; and Inv should be between those two values.");
                alert.showAndWait();
                return;
            }

            if(inhouseRADIOBTN.isSelected()) {
                partCompanyNameTXT.clear();
                int machineId = Integer.parseInt(partMachineIdTXT.getText());
                Inventory.addPart(new InHouse(id,  name,  price,  stock,  min,  max, machineId));
            }
            else {
                partMachineIdTXT.clear();
                String companyName = partCompanyNameTXT.getText();
                Inventory.addPart(new Outsourced(id,  name,  price,  stock,  min,  max, companyName));
            }

            stage = (Stage)((Button)event.getSource()).getScene().getWindow();
            scene = FXMLLoader.load(InventoryApplication.class.getResource("mainform-view.fxml"));
            stage.setScene(new Scene(scene));
            stage.show();
        }
        catch(NumberFormatException exception) {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Error");
            alert.setContentText("Please enter valid values into the text fields.");
            alert.showAndWait();
        }
    }

    /** This redirects a user back to the main form. */
    @FXML
    void  onActionMainForm (ActionEvent event) throws IOException {
        Alert alert = new Alert(Alert.AlertType.CONFIRMATION, "This will clear all text fields. Do you want to continue?");

        Optional<ButtonType> result = alert.showAndWait();

        if(result.isPresent() && result.get() == ButtonType.OK) {
            stage = (Stage)((Button)event.getSource()).getScene().getWindow();
            scene = FXMLLoader.load(InventoryApplication.class.getResource("mainform-view.fxml"));
            stage.setScene(new Scene(scene));
            stage.show();
        }
    }

}